# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mymind < Formula
  desc "The mymind API uses signed per-request JWT bearer tokens. Objects are saved URLs, notes, images, documents, videos, or files. Objects can have tags, spaces, notes, content, blobs, screenshots, and AI-generated metadata."
  homepage "https://github.com/nawwwal/mymind"
  version "1.3.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nawwwal/mymind/releases/download/v1.3.2/mymind_1.3.2_macos_intel.tar.gz"
      sha256 "79468384442f7dc4a0ff0565a86ab8e1206790812caaf5e2140dc89304cb1418"

      define_method(:install) do
        bin.install "mymind"
        bin.install "mymind-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nawwwal/mymind/releases/download/v1.3.2/mymind_1.3.2_macos_apple_silicon.tar.gz"
      sha256 "091b8aadaea6194df265cd2d2a3c412d4c93693278a96313223120715a85daed"

      define_method(:install) do
        bin.install "mymind"
        bin.install "mymind-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nawwwal/mymind/releases/download/v1.3.2/mymind_1.3.2_linux_x64.tar.gz"
      sha256 "435e0a6b252b401be6bdd5c9081fa145c238760ee2e2c703ec628e549b6c8f18"
      define_method(:install) do
        bin.install "mymind"
        bin.install "mymind-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nawwwal/mymind/releases/download/v1.3.2/mymind_1.3.2_linux_arm64.tar.gz"
      sha256 "6c20dd9228c27b8e80df77f90acf7883f43098ee18b08fa1d42106f7afea4f4e"
      define_method(:install) do
        bin.install "mymind"
        bin.install "mymind-mcp"
      end
    end
  end
end
